### PR TITLE
fixes #96 NewConnPipe can wait indefinitely on peer

### LINKED ISSUE #96: NewConnPipe can wait indefinitely on peer
_We are encountering a lock-up on a tlsctp REP listener if 1 incoming TLS/TCP connection is bad (ends prematurely). This could be a problem with other transports, too._

### Problem description

We are running mangos v1, which we pull from `git:nanomsg.org/go-mangos`. Occasionally it happens that `tlstcp.go:Accept()` fails. The failure has to do with `mangos.NewConnPipe()`.

The symptom in each case follows the same pattern as the gdb trace below:
```
(gdb) goroutine 61 bt
#0  runtime.gopark (lock=0x7f2bc5610708, reason=2 '\002', traceEv=27 '\033', traceskip=5, unlockf=<optimized out>) at /opt/go/src/runtime/proc.go:303
#1  0x0000000000446c2b in runtime.netpollblock (mode=114, pd=0x7f2bc56106e0, waitio=false, ~r3=<optimized out>) at /opt/go/src/runtime/netpoll.go:366
#2  0x00000000004462c8 in internal/poll.runtime_pollWait (mode=114, pd=0x7f2bc56106e0, ~r2=<optimized out>) at /opt/go/src/runtime/netpoll.go:173
#3  0x00000000004e687c in internal/poll.(*pollDesc).wait (isFile=false, mode=114, pd=0xc0003e0598, ~r2=...) at /opt/go/src/internal/poll/fd_poll_runtime.go:85
#4  0x00000000004e698f in internal/poll.(*pollDesc).waitRead (isFile=<optimized out>, pd=<optimized out>, ~r1=...) at /opt/go/src/internal/poll/fd_poll_runtime.go:90
#5  0x00000000004e76fb in internal/poll.(*FD).Read (fd=0xc0003e0580, p= []uint8 = {...}, ~r1=<optimized out>, ~r2=...) at /opt/go/src/internal/poll/fd_unix.go:169
#6  0x000000000057fd41 in net.(*netFD).Read (err=..., fd=<optimized out>, n=<optimized out>, p=...) at /opt/go/src/net/fd_unix.go:202
#7  0x00000000005936aa in net.(*conn).Read (b= []uint8 = {...}, c=0xc00000e258, ~r1=<optimized out>, ~r2=...) at /opt/go/src/net/net.go:177
#8  0x000000000067a97b in crypto/tls.(*block).readFromUntil (b=0xc0002a8900, n=5, r=..., ~r2=...) at /opt/go/src/crypto/tls/conn.go:492
#9  0x000000000067ae7f in crypto/tls.(*Conn).readRecord (c=0xc0001db880, want=23 '\027', ~r1=...) at /opt/go/src/crypto/tls/conn.go:593
#10 0x000000000067e433 in crypto/tls.(*Conn).Read (b=<error reading variable: access outside bounds of object referenced via synthetic pointer>, c=0xc0001db880, err=..., n=0)
    at /opt/go/src/crypto/tls/conn.go:1145
#11 0x000000000048140a in io.ReadAtLeast (buf= []uint8 = {...}, err=..., min=8, n=<optimized out>, r=...) at /opt/go/src/io/io.go:305
#12 0x00000000004815aa in io.ReadFull (buf=..., err=..., n=<optimized out>, r=...) at /opt/go/src/io/io.go:329
#13 0x00000000004bece0 in encoding/binary.Read (data=..., order=..., r=..., ~r3=...) at /opt/go/src/encoding/binary/binary.go:245
#14 0x0000000000ee5607 in nanomsg.org/go-mangos.(*conn).handshake (p=0xc0003d7540, props= []interface {} = {...}, ~r1=...)
    at /opt/TeamCity/buildAgent/work/34f7a3c3b5ec8423/server/syntropy3/src/go/src/nanomsg.org/go-mangos/conn.go:188
#15 0x0000000000ee510e in nanomsg.org/go-mangos.NewConnPipe (c=..., props=..., sock=..., ~r3=..., ~r4=...)
    at /opt/TeamCity/buildAgent/work/34f7a3c3b5ec8423/server/syntropy3/src/go/src/nanomsg.org/go-mangos/conn.go:141
#16 0x0000000000eef1e3 in nanomsg.org/go-mangos/transport/tlstcp.(*listener).Accept (l=0xc0003c90c0, ~r0=..., ~r1=...)
    at /opt/TeamCity/buildAgent/work/34f7a3c3b5ec8423/server/syntropy3/src/go/src/nanomsg.org/go-mangos/transport/tlstcp/tlstcp.go:176
#17 0x0000000000ee9a96 in nanomsg.org/go-mangos.(*listener).serve (l=0xc000498180)
    at /opt/TeamCity/buildAgent/work/34f7a3c3b5ec8423/server/syntropy3/src/go/src/nanomsg.org/go-mangos/core.go:687
#18 0x00000000004773e1 in runtime.goexit () at /opt/go/src/runtime/asm_amd64.s:1333
#19 0x000000c000498180 in ?? ()
#20 0x0000000000000000 in ?? ()
```

The call is stuck in `Accept()`:
```go
// tlstcp.go
func (l *listener) Accept() (mangos.Pipe, error) {
// ...
        return mangos.NewConnPipe(conn, l.sock,
                mangos.PropTLSConnState, conn.ConnectionState()) // <=== STUCK HERE
}
```

NewConnPipe was stuck in handshake:
```go
// conn.go
func NewConnPipe(c net.Conn, sock Socket, props ...interface{}) (Pipe, error) {
        p := &conn{c: c, proto: sock.GetProtocol(), sock: sock}

        if err := p.handshake(props); err != nil {  // <=== STUCK HERE
```

The `p.handshake` was stuck in binary read:
```go
//conn.go
func (p *conn) handshake(props []interface{}) error {
// ...

        h := connHeader{S: 'S', P: 'P', Proto: p.proto.Number()}
        if err = binary.Write(p.c, binary.BigEndian, &h); err != nil {
                return err
        }
        if err = binary.Read(p.c, binary.BigEndian, &h); err != nil { // <=== STUCK HERE
                p.c.Close()
                return err
        }
```

The binary read was stuck in `io.ReadFull`: 
```go
// encoding/binary/binary.go
func Read(r io.Reader, order ByteOrder, data interface{}) error {
// ...
        if _, err := io.ReadFull(r, d.buf); err != nil { // <== STUCK HERE
                return err
        }
        d.value(v)
        return nil
}
```

According to `io` documentation, [`ReadFull`](https://godoc.org/io#ReadFull) will block until it has read exactly `d.buf` bytes.
This would block indefinitely if the TLS connection does not have any more data in the pipeline (which is confirmed by the calls to net.(*netFD).Read,  runtime.netpollblock in the trace).

The `net.Conn` interface has a [`SetReadDeadline`](https://golang.org/pkg/net/#Conn) call which prevents hanging on read:
```go
type Conn interface {
// ...
    // SetReadDeadline sets the deadline for future Read calls
    // and any currently-blocked Read call.
    // A zero value for t means Read will not time out.
    SetReadDeadline(t time.Time) error
```
(There is a combined `SetDeadline` which sets both read/write timeouts.)

Currently the mangos v1 code does not call `SetDeadline` or `SetReadDeadline` . The [`tls.Conn`](https://golang.org/pkg/crypto/tls/#Conn) which is used by the tlstcp module implements `net.Conn`, but also no r/w deadline is set.

The _result_ is that the `PipeListener.Accept()` of the tlstcp module now becomes _blocking_, since it 
- does the net.Accept call (new incoming connection on the TLS/TCP socket),
- tries to read the SP header, but hangs.

It will hang in this place (core.go:687 in above gdb trace):
```go
// serve spins in a loop, calling the accepter's Accept routine.
func (l *listener) serve() {
        for {
                select {
                case <-l.sock.closeq:
                        return
                default:
                }

                // If the underlying PipeListener is closed, or not
                // listening, we expect to return back with an error.
                if pipe, err := l.l.Accept(); err == nil {  // <=== STUCK HERE
                     l.sock.addPipe(pipe, nil, l)
// ...
```

We are able to confirm this by looking at the host's connections. The tcp/tls listener is on 10.55.220.81:20083:
```bash
root@CA2ITSH-SRN-25:~# netstat -antp|grep 10.55.220.81:20083|awk '{print $6}'|sort |uniq -dc
    130 ESTABLISHED
      2 SYN_RECV
```

The incoming listener queue is full (we use the default 128 for somaxconn):
```bash
root@CA2ITSH-SRN-25:~# ss -l
...
tcp    LISTEN     129    128                                                    :::20083                                                                :::*    
```

We were able (via lsof -p) to identify the one hanging connection as `10.55.220.81:20083->172.25.1.9:57146 (ESTABLISHED)`
For this socket, the receive/send queues are empty on the receiving host:
```bash
root@CA2ITSH-SRN-25:~# ss -lona| grep 172.25.1.9:57146
tcp    ESTAB      0      0       ::ffff:10.55.220.81:20083                 ::ffff:172.25.1.9:57146 
```

On the _sending host_ (172.25.1.9), the connection with source port 57146 was long gone.

## Conclusion and proposed fix

The PipeListener.Accept is unlike the net.Conn.Accept, since it both reads/writes something on the connection before it returns.
In case of a _broken connection_, this will _hang_ since socket r/w deadlines are not set. There is currently no way to set them.

One way would be to see if `OptionRecvDeadline` and/or `OptionSendDeadline` are set by the caller, and to reuse that for the transport socket.
If not present, this could use some "sane" fallback (e.g. 1 second), to avoid blocking indefinitely.

### PR DESCRIPTION
**Pull request by gdamore**
This fixes an important security and reliability concern -- a some of the early negotiation logic was on a synchronous path for dialing, and this could allow a bad peer to either slow or completely stall out any new connections from being established.

The Dialer side is still synchronous, by necessity, as it only opens a single connection at a time.

### CODE REVIEW

**Comment by gdamore** [comment]
@grrtrr As this was your concern, I would appreciate it you could both review, and test this.  Sorry it took so long for me to find cycles to get to this -- it only took a few hours to put together, but life has been kind of hectic lately.

**Comment by grrtrr** [comment]
@gdamore This is great news and I am happy to help looking through this and with testing. It could be a little time due to other commitments, but I will be starting with this within the next days.

**Comment by gdamore** [comment]
The AppVeyor builds are all totally busted -- I think we have timing sensitive things in the test suite, and AppVeyor seems to run too slowly -- my guess is that there are reconnection things that take too long, or that we have delays expecting connections to be up, and those aren't, which ultimately lead to these failures.  On my Windows 10 laptop, the test suites pass flawlessly.

We may need to examine which of the tests are taking too long on AppVeyor.

I also want to look at moving the tests into individual protocol directories instead of the common tests tree, which may facilitate isolating them a bit more.  That's not for right now though.

File: transport/tcp/tcp.go [hunk 1]
```diff
@@ -125,7 +126,16 @@ func (d *dialer) Dial() (_ transport.Pipe, err error) {
...
+	p, err := transport.NewConnPipe(conn, d.proto, d.opts)
+	if err != nil {
+		conn.Close()
+		return nil, err
+	}
+	if err = d.handshaker.Start(p); err != nil {
+		conn.Close()
+		return nil, err
+	}
+	return d.handshaker.Wait()
```
Comment (grrtrr) [inline transport/tcp/tcp.go]: The combination of `Start` + `Wait` suspends the `Dial()` call until the `worker` has completed the handshake.
With tls+tcp we [ran into problems where the initial Dial() handshake never completed](https://github.com/nanomsg/mangos/issues/96#issuecomment-482187557), hence the Dial() code would still hang if the handshake never completed.

File: transport/tcp/tcp.go [hunk 2]
```diff
@@ -137,34 +147,49 @@ func (d *dialer) GetOption(n string) (interface{}, error) {
...
 	l.listener, err = net.ListenTCP("tcp", l.addr)
-	if err == nil {
-		l.bound = l.listener.Addr()
+	if err != nil {
+		return
 	}
+	l.bound = l.listener.Addr()
+	go func() {
+		for {
+			conn, err := l.listener.AcceptTCP()
```
Comment (grrtrr) [inline transport/tcp/tcp.go]: When the listener is Close()d, the goroutine continues to run (leaks) - maybe exit goroutine on this condition (on Linux `EINVAL`, not sure about Windows).

File: transport/conn.go [hunk 3]
```diff
@@ -191,3 +187,98 @@ func (p *conn) handshake() error {
...
+		item := h.doneq[0]
+		h.doneq = h.doneq[1:]
+		item.c.Close()
+	}
+	return nil
+}
+
+func (h *connHandshaker) worker(conn connHandshakerPipe) {
+	item := &connHandshakerItem{c: conn}
+	item.e = conn.handshake()
```
Comment (grrtrr) [inline transport/conn.go]: If the `conn.handshake()` never returns due to a bad connection (as in #96), the `worker()` goroutine would leak.

File: transport/tlstcp/tlstcp.go [hunk 4]
```diff
@@ -142,7 +143,16 @@ func (d *dialer) Dial() (transport.Pipe, error) {
...
+	p, err := transport.NewConnPipe(conn, d.proto, opts)
+	if err != nil {
+		conn.Close()
+		return nil, err
+	}
+	if err = d.handshaker.Start(p); err != nil {
+		conn.Close()
+		return nil, err
+	}
+	return d.handshaker.Wait()
```
Comment (grrtrr) [inline transport/tlstcp/tlstcp.go]: Same comments (also for Listener) as in tcp.go

File: transport/tlstcp/tlstcp.go [hunk 5]
```diff
@@ -179,9 +190,43 @@ func (l *listener) Listen() error {
 	if l.listener, err = net.ListenTCP("tcp", l.addr); err != nil {
 		return err
 	}
-
 	l.bound = l.listener.Addr()
 
+	go func() {
+		for {
+			tconn, err := l.listener.AcceptTCP()
+			if err != nil {
```
[the remark this answers is not in the document]
Comment (gdamore) [reply transport/tlstcp/tlstcp.go]: Good point.

File: transport/tcp/tcp.go (hunk 1 above)
Comment (gdamore) [reply transport/tcp/tcp.go]: Yes, that's correct.  The assumption here is that Dial() in the client is synchronous.  Most of the time this is appropriate.  For the cases where it isn't, the caller can set the OptionDialAsynch option, which basically causes this to run in a go routine.

File: transport/tcp/tcp.go (hunk 2 above)
Comment (gdamore) [reply transport/tcp/tcp.go]: Same issue as you already identified.

File: transport/tlstcp/tlstcp.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (gdamore) [reply transport/tlstcp/tlstcp.go]: Actually better than checking for syscalls is to setup a separate closeq channel that can be tested for after we get an error.  (We might also add a timeout here to reduce spinning).

File: transport/conn.go (hunk 3 above)
Comment (gdamore) [reply transport/conn.go]: handshake should fail eventually.  Arguably this might be a case where the timeouts would be useful ... to detect a stuck TCP session.  That said, normally that shouldn't be an issue.  Typically the kernel will eventually detect that the TCP peer is dead.

Having said that, I'd be willing to set some kind of reasonable timeout on the handshake in particular.  That's probably a different case.  (Probably the timeout should be a small number of seconds -- under normal circumstances the handshake should complete within a few round trip times.)

File: transport/handshaker.go [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+// stalling the server's accept queue.  This is important to
+// ensure that a slow remote peer cannot bog down the server
+// or effect a denial-of-service for new connections.
+type Handshaker interface {
+	// Start injects a pipe into the handshaker.  The
+	// handshaking is done asynchronously on a Go routine.
+	Start(Pipe) error
+
+	// Waits for until a pipe has completely finished the
+	// handshaking at returns it.
```
[the remark this answers is not in the document]
Comment (gdamore) [reply transport/handshaker.go]: Fixed.

File: transport/handshaker.go [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+	Wait() (Pipe, error)
+
+	// Close is used to close the handshaker.  Any existing
+	// negotiations will be canceled, and the underlying
+	// transport sockets will be closed.  Any new attempts
+	// to start will return a closed error.
```
[the remark this answers is not in the document]
Comment (gdamore) [reply transport/handshaker.go]: Fixed.

File: transport/conn.go (hunk 3 above)
Comment (gdamore) [reply transport/conn.go]: I'd like to handle setting the timeout for this (to close the potential leak of the file and associated go routine) separately.  That "leak" (I'd argue its not really a leak, as the peer could actually wake up and complete the operation some long time - days even! - later) is a far less bad situation than we have where a the bad peer would actually gum up everything immediately, which this PR fixes.

File: transport/tcp/tcp.go (hunk 1 above)
Comment (grrtrr) [reply transport/tcp/tcp.go]: Oh, I was talking from the v1 perspective, which used DialAsynch. In our case, it [got stuck](https://github.com/nanomsg/mangos/issues/96#issuecomment-482187557) and was never able to report an error, causing the application to hang.

**Comment by grrtrr** [comment]
@gdamore - I want to thank you for your willingness and perseverance to address this issue. I am concerned about the complexity, since all of this will interact with the other moving parts of mangos.
The dialer and listener now have internal state which interacts with the state of the rest of the system. As we experienced on our system, the tcp+tls Dialer can also hang on a bad TLS handshake.

Using timeouts for the r/w operations would also address the 'blocked' problem that this PR addresses. It is simpler and would also help to recover from stuck connections. I don't know how long it takes the kernel to do this, but I think it has to to with keep-alive timeout, which could be hours. Timeouts would be simpler and likewise address the problem.

When it comes to testing, I am sorry I misunderstood initially. Our system is still running on mangos-v1, I need to get buy-in here to upgrade. This means talking back and forth, I might be able to run independent tests, but they would not be as meaningful.

**Comment by gdamore** [comment]
@grrtrr I'm fairly confident that the moving parts are isolated from this -- the timeouts may help, and I'm open to adding them in a follow up PR.  I particularly believe that the *handshake* portion of the setup should have a reasonably aggressive timeout, because there is no reason for a peer to timeout -- probably I'd set that up in the range of a single digit number of seconds.  (I'm thinking like "5".)

Still, setting up those timeouts was not itself sufficient, to my thinking.  In particular, it seems really onerous that a slow peer can interfere with (or prevent) a well-behaved one from connecting.

I'm likely to move ahead with this PR for mangos v2.  I may follow up (probably will if nobody else does) a follow up to add a timeout during the handshake.  (connection timeouts during the rest of the protocol may be tunable too, but I consider that orthogonal as there are perfectly sane situations where a connection can be long lived with no traffic, but in other situations where that would be inappropriate.)

For mangos v1, we'd probably settle for something much simpler -- like a default timeout during the handshake phase only.  That might help you over the hump.  Again, I'd set that for something like 5 seconds.

**Comment by grrtrr** [comment]
@gdamore Ok, I have to step back to [this conversion](https://github.com/nanomsg/mangos-v1/pull/348) to explain why I am uncomfortable with the "correct" fix. I do not understand your aversion against read/write timeouts. In the above you are saying you would be ok to adding a timeout to the handshake portion. Good, if we are using a timeout for that, why can we not use r/w timeouts in the first place? 

To avoid using them, additional code is added, which has to work with 4 different socket types and 22 different protocols (number of directories I counted underneath `protocol/`). It is the interaction of this and the other parts that makes me uncomfortable. Looks great in isolation, but debugging this in production seems difficult without attaching a debugger to the live instance. The timeouts in https://github.com/nanomsg/mangos-v1/pull/348 have worked for 3 months in the environments we regularly saw TLS handshakes fail (both client Dial and listener Accept failures), and they are simple.

Going back to that earlier conversation, you mentioned two design decisions that in my understanding you considered essential:
1. nanomsg connections are long-lived.
2. Failed connections are cleaned up using the TCP KeepAlive mechanism.

Both are creating issues for us. First the REQ/REP socket type uses short-lived connections (1) for doing reliable RPC. This is our main use-case. I have not used the other socket types much, but imagine 
there may be other short-lived interactions, e.g. publishing a message on a pub/sub basis. With regard to the KeepAlive mechanism (2), this is insufficient as feedback, as the timeouts are in the order of hours. When doing an RPC, we need to know within about a minute if it worked or not, in order to react to it. 

In addition, there are 2 advantages of using r/w timeouts. First, the (`tcp` or `tls+tcp`) connection can die anytime, without timeouts on the socket, it would cause problems not only during handshake, but also mid-protocol. The other is that the API returns a distinct error (`TimeoutError`) which can be used to direct the strategy on the upper layers.

**Comment by gdamore** [comment]
@grrtrr So I need to respond to a few things.  First, I want to elaborate that I don't believe that this PR should preclude the addition of timeouts, for users that want to use them.  But the key issue for me is that a single peer can interfere with forward progress by another peer, is not adequately resolved by timeouts.  I also think relying upon timeouts as a silver bullet is misguided, and far less safe than you believe -- this based on my deep experience, but I will elaborate specifically here.

1. The orginal design was that we would not add a pipe to the socket until it is fully established.  The original design intent was that no single peer should be able to detrimentally impact other peers.  This PR addresses the failure to deliver on that intent. 
2. Because the rest of the system was designed with said intent in mind, I'm far, far less concerned about possible ramifications.  As the creator of this software, I feel completely confident that running the handshake in a go routine is right and proper.  In fact, the websocket implementation effectively already does this.
3. As to timeouts instead of this, the concern is that all other connecting peers would have to wait behind another negotiating pipe, at least until that pipe finishes it's negotiation.  This punishes good peers unduly.
4. This may actually cause otherwise functioning peers to *also* be terminated (perhaps at the other peer, which might see our failure to run the negotiation as a sign that we are *not* a good peer, because we're waiting for some other bad peer to either negotiate or timeout.  This is a problem of cascading timeouts.  I believe your approach does not adequately consider this.
5. The addition of timers, in general, in my experience, rarely *simplifies* design.  Instead most of the times they are a hack to work around conditions that we wish we didn't happen, and more often their addition leads to unforeseen consequences and challenges.  Put succicently, I don't have a warm fuzzy about timers and timeouts, and I tend to lean towards designs that are not fundamentally dependent upon them.

So, having said all that, I don't believe that timeouts alone are a solution to the problem.  They might improve a bad situation, but they are nothing more than a band-aid over a design defect.  I prefer to address the defect at it's root, which is the failure to run this handshake truly concurrently.

Now, the other side of the question, is whether timeouts have uses *in addition* to this PR.

I believe that they are in some cases useful.  Certainly, the handshaking phase should never stall for long periods of time, and it makes sense to reap connections where the peer is not making progress in a timely fashion.  So I do support (as I've said above) the idea of adding a timeout to the handshake phase -- probably 5 seconds is about right.  This also would address the concern about a synchronous Dialer getting stuck by a hung server.  (For various reasons, I still believe Dialing should be done synchronously -- the poor impact a bad server has on a dialer is not going to effect anything other than the go routine doing the Dial, which should only impact a single peer on the socket.)

As to timeouts *post* handshake, those are not at all a cut and dried answer.  There are use cases where very long periods of inactivity are perfectly reasonable.  We use keep alives today to prevent them from getting stuck *forever*, but generally that shouldn't be a concern for most use cases.

A peer pipe stuck in normal (post-handshake) phase communications will generally not impact more than a single (or possibly two) message worth of transaction, because until the message is properly delivered, flow control conditions will prevail and the pipe will not be returned to the ready queue for the socket.  This is a data loss situation, but the upper layer protocols should deal with this (either because they are lossy by design such as PUB/SUB, or they have their own recovery mechanisms such as REQ/REP.)  So really the only consequence for a stuck pipe in this situation is the loss of access to the resources (file descriptor, memory) that are consumed. 

I do recognize that there are deployment situations where even the resource leak is a concern, and where it also might be desirable to more proactively prune sessions than normal keep alives would give us.  A classic situation might be where you have a great number of mobile clients, that might roam off network, be powered down, etc.  If you know that this is a concern for your application, then a non-handshake timeout makes sense still, but I would consider that (and the desire for a handshake phase timeout as well) as orthogonal issues to be addressed separately from the core design defect that *this* PR addresses.

**Comment by gdamore** [comment]
I will be merging this PR.  I've heard your concerns, and posted my response.   We can follow up with PRs to add timeouts after if you like.

**Comment by grrtrr** [comment]
@gdamore - Thank you for the response. Since we seem to be talking from different viewpoints, I would like to clarify. First, when it comes to the design of the software (points 1,2) - that is clearly your call, and  not for me to say. We are grateful for all the work you have been putting in to make this implementation as flawless and robust to a high standard.

With regard to (3,4), yes it implies a _default timeout_. In addition to the problem you mentioned, it can be tricky to come up with the right one.

In all this I want to clarify that by timeout in this discourse I _only_ mean the [read/write timeout](https://godoc.org/net#TCPConn.SetDeadline) on an established TCP connection.
So all this is _only_ applicable to the `tcp` and `tcp+tls` protocols. And, really, I have only seen the problem with TLS connections, and then only in one particular cloud environment (Azure).
We would have a bad tcp+tls connection on the order of days, and otherwise no failure. For this scenario, timeouts (without above) fix were fully adequate.

This brings me to why I think that timeouts _do_ have a place. When doing a read or write on an established TCP connection, the assumption without a timeout is that [the network is reliable](https://queue.acm.org/detail.cfm?id=2655736). The number of middleboxes and boxes on the path of a connection keeps growing, due to the use of network virtualization (VPC) and software-defined networking. So in regard to (5), the network is not something the software can control.

It took us quite a while to fine-tune the timeouts that the REQ/REP socket uses (and it has quite a few), so I was already used to thinking in timeouts to deal with networking situations. By implication I thought you would consider timeouts as part of the whole picture. Network deployments differ, so the ability to adapt parameters to a particular network is important (compare e.g. backbone with mobile clients).

**Comment by gdamore** [comment]
@grrtrr if we want to introduce timeouts *as well* as this PR, as I indicated, I'm fine with that -- I don't believe they should be on by default, but introducing a tunable to give applications an ability to prevent those days-long hangs is a good idea.  (Arguably if this is occurring then something is horribly wrong with the TCP keep-alive implementation in the peer systems.  This should have nothing to do with middleboxes unless they are screwing around with the TCP connection itself, which would be incredibly bad form.  I can see some kind of TCP proxy mishandling this though.)

Nonetheless, I will consider timeouts (both during handshake, and on established connections) as a separate issue, to be handled via a separate PR.
